import { ObjectId } from 'mongodb';

/**
 * Represents a feed.
 * - `userId`: The unique identifier of the user to whom the feed belongs.
 * - `lastViewedRanking`: The last viewed ranking in the feed.
 */
export interface Feed {
  userId: ObjectId;
  lastViewedRanking: number;
}

/**
 * Represents a Feed document in the database.
 * - `_id`: The unique identifier for the feed, generated by MongoDB.
 * - `userId`: The unique identifier of the user to whom the feed belongs.
 * - `lastViewedRanking`: The last viewed ranking in the feed.
 */
export interface DatabaseFeed extends Feed {
  _id: ObjectId;
}

/**
 * Represents the response for Feed-related operations.
 * - `Feed`: A feed object if the operation is successful.
 * - `error`: An error message if the operation fails.
 */
export type FeedResponse = DatabaseFeed | { error: string };
